FROM python:3.6-alpine

WORKDIR /app

RUN apk add --no-cache --update make

COPY flask_app.py /app

RUN pip3 install flask && pip3 install gunicorn

CMD ["gunicorn", "flask_app", "--bind", "0.0.0.0:8085"]