version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8090:8090"
  redis:
    image: "redis:alpine"
    container_name: redisbackend
    ports:
        - "6389:6389"

  # python-counter-app:
  #   build: ./python-counter-app
  #   image: python:3.9-alpine
  #   container_name: python-counter-app
  #   environment:
  #     REDIS: redisbackend
  #   ports:
  #       - "80:80"