apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: python-counter-app-cert
  namespace: cert-manager
spec:
  secretName: python-counter-app-cert
  issuerRef:
    name: buypass
    kind: ClusterIssuer
  dnsNames:
    - "python-counter-app.local"
