apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: python-counter-app
  namespace: python-counter-app
spec:
  secretName: python-counter-app-cert
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - "python-counter-app.local"
