apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: python-counter-app-cert
  namespace: cert-manager
spec:
  secretName: letsencrypt-prod
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "python-counter-app.local"
