apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-counter-app
  namespace: python-counter-app
  labels:
    app: python-counter-app
spec:
  selector:
    matchLabels:
      app: python-counter-app
  replicas: { .Values.replicaCount | quote }
  template:
    metadata:
      labels:
        app: python-counter-app
    spec:
      containers:
        name: { .Values.image-name | quote }
        image: { .Values.image-repository | quote }
        imagePullPolicy: { .Values.image-pullPolicy | quote }
        ports:
          name: http
          containerPort: { .Values.service-containerPort | quote }
          protocol: { .Values.service-protocol | quote }
        volumeMounts:
          name: config-volume
          mountPath: /helm/templates/
      volumes:
        name: config-volume
        configMap:
          name: application-settings
      env:
        name: { .Values.env-name | quote }
        value: { .Values.env-value | quote }
