---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-counter-app
  namespace: python-counter-app
  labels:
    app: python-counter-app
spec:
  selector:
    matchLabels:
      app: python-counter-app
  replicas: {{.Values.replicaCount}}
  template:
    metadata:
      labels:
        app: python-counter-app
    spec:
      containers:
        - name: {{.Values.image.name}}
          image: {{.Values.image.repository}} 
          #:{{.Values.image.tag1 | default .Value.image.tag2}}
          imagePullPolicy: {{.Values.image.pullPolicy}}
          ports:
            - name: http
              containerPort: {{.Values.service.containerPort}}
              protocol: {{.Values.service.protocol}}
          volumeMounts:
            - name: config-volume
              mountPath: /config
          livenessProbe:
            httpGet:
              port: http
          readinessProbe:
            httpGet:
              port: http
      volumes:
        - name: config-volume
          configMap:
            name: application-settings
      env:
        - name: {{.Values.env.name}}
          value: {{.Values.env.value}}
