apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-counter-app
  namespace: python-counter-app
  labels:
    app: python-counter-app
spec:
  selector:
    matchLabels:
      app: python-counter-app
  replicas: { { .helm.Values.replica } }
  template:
    metadata:
      labels:
        app: python-counter-app
    spec:
      containers:
        - name: { { .Chart.Name } }
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: { { .Values.image.pullPolicy } }
          ports:
            - name: http
              containerPort: { { .Values.service.containerPort } }
              protocol: { { .Values.service.protocol } }
          volumeMounts:
            - name: config-volume
              mountPath: /config
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
      volumes:
        - name: config-volume
          configMap:
            name: application-settings
      env:
        - name: { { .Values.env.name } }
          value: { { .Values.env.value } }
