apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python-counter-app
  name: python-counter-app
  namespace: python-counter-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-counter-app
  strategy: {}
  template:
    metadata:
      labels:
        app: python-counter-app
    spec:
      containers:
        - image: "{{ .Values.image.repository }}"
          name: "{{ .Values.image.name }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
              initialDelaySeconds: 3
              periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
              initialDelaySeconds: 3
              periodSeconds: 3
          ports:
            - containerPort: "{{ .Values.service.port }}"
              name: http
              protocol: "{{ .Values.service.protocol }}"
          resources:
            requests:
              cpu: "{{ .Values.resources.requests.cpu }}"
              memory: "{{ .Values.resources.requests.memory }}"
            limits:
              cpu: "{{ .Values.resources.limits.cpu }}"
              memory: "{{ .Values.resources.limits.memory }}"
          volumeMounts:
            name: config-volume
            mountPath: "./helm/templates/"
      volumes:
        name: config-volume
        configMap:
          name: application-settings
      env:
        name: "{{ .Values.env.name }}"
        value: "{{ .Values.env.value }}"
status: {}
