apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python-counter-app
  name: python-counter-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-counter-app
  strategy:
    rollingUpdate:
      maxSurge: "25%"
      maxUnavailable: "25%"
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: python-counter-app
    spec:
      containers:
        - image: dhackbility/python-counter-app:1.0.0
          name: python-counter-app
          imagePullPolicy: IfNotPresent
          env:
            - name: "http"
              value: 8087
          ports:
            - containerPort: 80
              name: "http"
              protocol: TCP
              hostPort: 8087
          volumes:
            - name: config-volume
              configMap:
                name: application-settings
              volumeMounts:
                name: config-volume
                mountPath: /
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
              scheme: HTTP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
              scheme: HTTP
          resources:
            requests:
              cpu: 250m
              memory: 64mi
            limits:
              cpu: 500m
              memory: 128Mi
      dnsPolicy: Default
