apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python-counter-app
  name: python-counter-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-counter-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: python-counter-app
    spec:
      containers:
        - image: dhackbility/python-counter-app:1.0.0
          name: python-counter-app
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 5
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: "250m"
              memory: "64mi"
            limits:
              cpu: "500m"
              memory: "128Mi"
          volumeMounts:
            name: config-volume
            mountPath: /
      dnsPolicy: Default
      volumes:
        - name: config-volume
          configMap:
            name: application-settings
      env:
        - name: http
          value: 8087
