apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-counter-app-ingress
  namespace: python-counter-app
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    - hosts:
        - python-counter-app.local
      secretName: letsencrypt-prod
  ingressClassName: nginx
  rules:
    - host: python-counter-app.local
      http:
        paths:
          - backend:
              service:
                name: python-counter-app-svc
                port:
                  number: 8085
            path: /
            pathType: Prefix
          - backend:
              service:
                name: redis
                port:
                  number: 6379
            path: /
            pathType: Prefix
