apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-counter-app-route
  namespace: python-counter-app
  annotations:
    cert-manager.io/cluster-issuer: bp-issuer
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
    - hosts:
        - python-counter-app.local
      secretName: python-counter-app-cert
  ingressClassName: nginx
  rules:
    - host: python-counter-app.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: python-counter-app-svc
                port:
                  number: 80

    - host: python-counter-app.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: python-counter-app-svc
                port:
                  number: 6379
