apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: bp
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: python-counter-app-route
  namespace: default
spec:
  tls:
    - hosts:
        - python-counter-app.local
      secretName: python-counter-app-cert
  ingressClassName: nginx
  rules:
    - host: "python-counter-app.local"
      http:
        paths:
          - backend:
              service:
                name: python-counter-app-svc
                port:
                  name: http
                  number: 80
    - host: "python-counter-app.local"
      http:
        paths:
          - backend:
              service:
                name: python-counter-app-service
                port:
                  name: redis
                  number: 6379
