apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: bp
  namespace: cert-manager
spec:
  acme:
    email: taofeekaoyusuf@gmail.com
    server: https://api.buypass.com/acme/directory
    privateKeySecretRef:
      name: bp-issuer-account-key
    solvers:
      - http01:
          ingress:
            class: nginx

  # acme:
  #   email: taofeekaoyusuf@gmail.com
  #   server: https://api.buypass.com/acme/directory # https://acme-v02.api.letsencrypt.org/directory
  #   privateKeySecretRef:
  #     name: buypass-issuer-account-key
  #   solvers:
  #     - http01:
  #         ingress:
  #           class: nginx
