apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: buypass
spec:
  acme:
    email: taofeekaoyusuf@gmail.com
    storage: acme.json
    caServer: https://api.buypass.com/acme/directory 
    keyType: EC256
    httpChallenge:
      entryPoint: web
    solvers:
      - http01:
          ingress:
            class: nginx

  # acme:
  #   email: taofeekaoyusuf@gmail.com
  #   server: https://api.buypass.com/acme/directory # https://acme-v02.api.letsencrypt.org/directory
  #   privateKeySecretRef:
  #     name: buypass-issuer-account-key
  #   solvers:
  #     - http01:
  #         ingress:
  #           class: nginx
