apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    email: taofeekaoyusuf@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            name: python-counter-app-ingress
            class: nginx

  # acme:
  #   email: taofeekaoyusuf@gmail.com
  #   server: https://acme-v02.api.letsencrypt.org/directory
  #   privateKeySecretRef:
  #     name: buypass-issuer-account-key
  #   solvers:
  #     - http01:
  #         ingress:
  #           class: nginx
