apiVersion: v1
kind: Service
metadata:
  labels:
    app: klein
  name: python-counter-app
  namespace: python-counter-app
spec:
  ports:
    - name: http
      port: 8081
      targetPort: http
  selector:
    app: klein
  type: LoadBalancer
