apiVersion: v1
kind: Service
metadata:
  labels:
    app: python-counter-app
  name: python-counter-app-svc
  namespace: python-counter-app
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: "{{ .Values.service.protocol }}"
      name: "{{ .Values.service.name }}"
  selector:
    app: python-counter-app
  type: ClusterIP
