apiVersion: v1
kind: Service
metadata:
  name: python-counter-app-svc
  namespace: default
  labels:
    app: python-counter-app-svc
spec:
  selector:
    app: python-counter-app
  type: LoadBalancer
  ports:
    host: "{{ .Values.serviceHost }}"
    servicePort: "{{ .Values.containerPort }}"
    targetPort: "{{ .Values.serviceTargetPort }}"
    Protocol: "{{ .Values.serviceProtocol }}"
