apiVersion: v1
kind: Service
metadata:
  labels:
    app: python-counter-app
  name: python-counter-app
  namespace: python-counter-app
spec:
  ports:
    - port: 80
      targetPort: 8087
      protocol: "TCP"
    - port: 6379
      targetPort: 6379
      protocol: "
  selector:
    app: python-counter-app
  type: ClusterIP
