apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-counter-app-sandbox
  namespace: argocd
spec:
  project: python-counter-app
  source:
    helm:
      valueFiles:
        - values.yaml
    repoURL: https://github.com/taofeekaoyusuf/python-counter-app
    path: python-counter-app
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    path: ./helm/templates/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoredResources:
  - group: argoproj.io
  - group: apps
  - group: batch
  healthChecks:
  - name: check-cluster
    interval: 3m0s
    timeout: 3m0s
