apiVersion: v2
name: python-counter-app
appVersion: latest
description: Python Counter Application
version: 1.0.0
keywords:
  - python
  - redis
maintainers:
  - name: taofeekaoyusuf
    email: taofeekaoyusuf@gmail.com