apiVersion: v2
name: python-counter-app
appVersion: latest
description: Python counter application
version: 0.1.0
keywords:
  - python
  - redis
maintainers:
  - name: taofeekaoyusuf
    email: taofeekaoyusuf@gmail.com