replicas: 3

# image:
imageName: python-counter-app
imageRepository: dhackbility/python-counter-app:1.0.0
imagePullPolicy: IfNotPresent
imageTag: 1.0.0

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# service:
serviceType: ClusterIP
servicePort: 80
serviceTargetPort: 8090
serviceProtocol: TCP
serviceHost: python-counter-app.local
containerPort: 80

livenessProbe:
    path: /healthz
    port: 80
readinessProbe:
    path: /healthz
    port: 80

resources: 
  requests: 
    memory: 64Mi
    CPU: 250m
  limits:
    memory: 128Mi
    CPU: 500m

ingress-enabled: true
ingress-hosts: python-counter-app.local

## Application level settings  
appMode: production

envName: http
envValue: 8090
