replica: 1

image:
  repository: dhackbility/python-counter-app
  pullPolicy: IfNotPresent
  tag: v1.0.0

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 8081
  containerPort: 80
  protocol: TCP
  host: python-counter-app.local

ingress:
  enabled: true
  hosts:
  - python-counter-app.local

## Application level settings  
appMode: sandbox

env:
  - name: http
    value: 8080
