replicaCount: !!int 3

image:
  name: python-counter-app
  repository: dhackbility/python-counter-app
  pullPolicy: IfNotPresent
  tags: 1.0.0

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: !!int 80
  targetPort: !!int 8087
  protocol: !!str "TCP"

livenessProbe:
    path: /healthz
    port: !!int 80
readinessProbe:
    path: /healthz
    port: !!int 80

resources: 
  requests: 
    memory: 64Mi
    CPU: 250m
  limits:
    memory: 128Mi
    CPU: 500m

ingress-enabled: true
ingress-hosts: python-counter-app.local

## Application level settings  
appMode: production

env:
  name: http
  value: !!int 8087
