replicaCount: !!int 3

# image:
imageName: python-counter-app
imageRepository: dhackbility/python-counter-app:1.0.0
imagePullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# service:
type: ClusterIP
port: !!int 80
targetPort: !!int 8087
protocol: TCP
name: python-counter-app.local

livenessProbe:
    path: /healthz
    port: !!int 80
readinessProbe:
    path: /healthz
    port: !!int 80

resources: 
  requests: 
    memory: 64Mi
    CPU: 250m
  limits:
    memory: 128Mi
    CPU: 500m

ingress-enabled: true
ingress-hosts: python-counter-app.local

## Application level settings  
appMode: production

envName: http
envValue: !!int 8087
