replicaCount: "3"

image:
  repository: dhackbility/python-counter-app
  pullPolicy: IfNotPresent
  tag1: "1.0.0"
  tag2: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: "8081"
  containerPort: "80"
  protocol: TCP
  host: python-counter-app.local

ingress:
  enabled: true
  hosts:
  - python-counter-app.local

## Application level settings  
appMode: production

env:
  - name: http
    value: "8080"
