replicas: 2

# image:
imageName: python-counter-app
imageRepository: dhackbility/python-counter-app:1.0.0
imagePullPolicy: IfNotPresent
imageTag: 1.0.0

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# service:
serviceType: ClusterIP
servicePort: 80
serviceTargetPort: 8090
serviceProtocol: TCP
serviceHost: python-counter-app.local

ingress-enabled: true
ingress-hosts: python-counter-app.local

## Application level settings  
appMode: staging

envName: http
envValue: 8090
